.gitignore
Makefile
README.md
deploy/k8s.yaml
service/Dockerfile
service/go.mod
service/go.sum
service/main.go

The basic implementation of the app

The basic implementation of the app

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md

fixes #2 
Signed-off-by: ashiscs <ashissingh640@gmail.com>

Added Issue Templates

---

.github/workflows/ci.yml
Makefile

Github CI to Build and push docker image.

CI for learn-layer5

---

deploy/k8s.yaml
service/main.go

@leecalcote I verified that the image on docker hub does work. Also, I have made some fixes so that the services will be able to identify which service made a request to them.

Fixes and service naming

---

.github/workflows/slack.yml

fixes #7 
Signed-off-by: ashiscs <ashissingh640@gmail.com>

Added slack notifier for github stars

---

.github/workflows/ci.yml

Signed-off-by: Lidor Ettinger <lidor.ettinger@gmail.com>

Adding tag release for docker images

---

.github/config.yml

Signed-off-by: morrme <morrme@users.noreply.github.com>
@leecalcote please re-review :) 
- [ x] Yes, I signed my commits.

[chore] fix image rendering

---

smi-conformance/Dockerfile
smi-conformance/test-gen/test_gen.go

fixed docker and result

---

.github/workflows/release-drafter.yml

Signed-off-by: anita-ihuman <charlesanita403@gmail.com>

 Added github action workflow

---

smi-conformance/test-gen/test_gen.go

fixed minor bug for reading yamls

---

smi-conformance/grpc/handlers.go
smi-conformance/test-gen/test_gen.go

modified results struct to return results

---

smi-conformance/test-gen/test_gen.go

modified timeouts in smi-conformance

---

.github/releasedrafter.yml

fix: releaseDrafter config file

---

smi-conformance/main.go

Signed-off-by: Efereyan Karen Simisola <thedevkaren@gmail.com>
This PR fixes #54
- [x ] Yes, I signed my commits.

Update reserved port from 10008 to 10011

---

smi-conformance/main.go

Signed-off-by: Gerald Maboshe <maboshegerald1@gmail.com>
Changed gokit package dependancy reference from kumarabd to layer5io
This PR fixes #55 
Build succeeded after changing the reference

Updated Reference to Gokit Package Dependency

---

service/Dockerfile

fixes for service docker-image

---

smi-conformance/manifest.yml

Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>
This PR adds smi-conformance manifest generated from the helm charts.
Should the charts directory be removed now that we intent to use the manifests for smi-conformance?

Add manifest generated from helm charts

---

smi-conformance/go.sum
smi-conformance/grpc/handlers.go
smi-conformance/manifest.yml

Co-authored-by: abishek <kumarabd@users.noreply.github.com>
Signed-off-by: dhruv0000 <patel.4@iitj.ac.in>
This PR fixes: 
- The percentage calculations
- Fixed [#37](https://github.com/layer5io/meshery-adapter-library/issues/37)
- Updated smi-conformance service to `LoadBalancer`
- Need to change `dhruv0000/learn-layer5:smi` in `smi-conformance/manifest.yaml` to `layer5/learn-layer5:smi`, once approved.

Updated Manifest and some SMI Changes

---

README.md

Added community forum to readme 

---

README.md

Signed-off-by: Ritvik Shukla <ritvikshukla261@gmail.com>
This PR fixes #79 

fixes issue #79 Added Slack Badge 

---

README.md

Signed-off-by: Nishant Mittal <mittalnishant14@outlook.com>
Was going through the project and saw a minor typo in the README.

fix: minor readme typo

---

.github/workflows/slack.yml

This PR fixes #94 
Signed-off-by : [jigarrathod2704@gmail.com](mailto:jigarrathod2704@gmail.com)
Updated the slack.yml file

Resolved Github actions Slack job failure
